main/urls.py
from django.urls import path

from . import views

urlpatterns = [
path("", views.home, name="home"),
path("home/", views.home, name="home"),
path("profile/", views.profile, name="profile"),
path("profile/account/", views.accountSettings, name="account"),
path('all/', views.AllView.as_view(), name='all'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as v
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('main.urls')),
    path('',include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
    path('register/', v.register, name="register"),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # add question (poll)
    path('create/',views.create, name='create'),
    # add options
    path('options/<int:id>/',views.options, name='options'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user   = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default = 'default.jpg', upload_to = 'dp')
    def __str__(self):
        return f'{self.user.username} Profile'

class Question(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <=now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class Votes(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)

polls/forms.py
from django import forms

class CreateListForm(forms.Form):
	name = forms.CharField(label="Name ", max_length=200,widget=forms.TextInput(attrs={'size':'60'})) 

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import Question, Choice, Votes
from .forms import CreateListForm
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages 


# Create your views here.

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
            Return published questions
        """
        return Question.objects.filter(
            pub_date__lte = timezone.now()
        ).order_by('-pub_date')


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/detail.html' 
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if Votes.objects.filter(question_id=question, user_id=request.user).exists():
        # WHY THE BELOW CODE DOESNT WORK?
        # return render(request, 'polls/detail.html', {
        # 'question': question,
        # 'error_message': "You have already voted for this question."
        # })
        messages.success(request, 'Already voted for the question')
        return redirect('/polls/',permanent=True)
        # return HttpResponseRedirect('polls/index.html')

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # save vote
        v = Votes(question_id = question, user_id=request.user)
        v.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

@login_required
def create(request):
    if request.method == "POST":
        form = CreateListForm(request.POST)
        print('a')
        if form.is_valid():
            n = form.cleaned_data['name']
            q = Question(user_id=request.user, question_text=n, pub_date=timezone.now())
            q.save()      
            return HttpResponseRedirect('/polls/options/%i'%q.id)
    else:
        form = CreateListForm()
    return render(request, 'polls/create.html',{"form":form})

@login_required
def options(request, id):
    ls = Question.objects.get(id=id)
    if request.user != ls.user_id:
        return redirect('/all/',permanent=True)
    if request.method =='POST':
        if request.POST.get('save'):
            for item in ls.choice_set.all():
                p = request.POST
                if "text"+str(item.id) in p:
                    item.choice_text = p.get("text"+str(item.id))
                item.save()
            return redirect('/all/', permanent=True)
        elif request.POST.get('add'):
            newChoice = request.POST.get('new')
            if newChoice != '':
                ls.choice_set.create(choice_text = newChoice, votes = 0)
            else:
                print("Invalid choice")
    return render(request, 'polls/options.html', {'ls':ls})

polls/templates/polls/create.html
{% extends 'main/base.html' %}
{% block title %}
Create New List
{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
	<h3>Create a new Question</h3>
	<br>
	<form method="post", action={% url 'polls:create' %} class="form-group">
		{% csrf_token %}
		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
			  <button name="save", type="submit", class="btn btn-success">Create</button>
			  {{form.name}}
	  		</div>  
		</div>
	</form>
{% endblock %}

polls/templates/polls/detail.html

{% extends "main/base.html" %}


{% block title %}
Question page
{% endblock %}

{% load static %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/radio-style.css' %}">
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<ul>
<div class="container">
    <h2>{{ question.question_text }}</h2>
    {% for choice in question.choice_set.all %}
    <li>
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <div class="check"></div>
    </li>
    {% endfor %}
    <input class="button button5" type="submit" value="Vote">
</div>
</ul>
{% endblock %}

polls/templates/polls/index.html
{% extends "main/base.html" %}

{% block title %}
Poll page
{% endblock %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/radio-style.css' %}">
<style>
    .card {
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
      transition: 0.3s;
      width: 80%;
      padding: 20px;
      border-radius: 15px;
      margin-bottom: 10px;
    }
    
    .card:hover {
      box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }
</style>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    {% for question in latest_question_list %}
        <div class="card">
            <a href="{% url 'polls:detail' question.id %}" style="text-decoration: none;">
                {{ question.question_text }}</a>
        </div>
    {% endfor %}
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert" id='message_container'>{{ message }}</div>
    {% endfor %}
{% endif %}
<script>
    var message_ele = document.getElementById("message_container");
    setTimeout(function(){ 
    message_ele.style.display = "none"; 
    }, 1000);
</script>
{% endblock %}

polls/templates/polls/options.html
{% extends 'main/base.html' %}

{% block title %}Option List{% endblock %}
 
{% block content %}
	<h2>{{ls.name}}</h2>
	<form method="post", action="#">
		{% csrf_token %}

		{% for item in ls.choice_set.all%}
			<div class="input-group mb-3">
	  			<input type="text" name="text{{item.id}}" value="{{item.choice_text}}" class="form-control" aria-label="Text input with checkbox">
			</div>
		{% endfor %}

		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
	  		<button name="add", value="add", type="submit", class="btn btn-success">Add option</button>
	  		</div>
	  		<input type="text" name="new" value="" class="form-control">
	  		
		</div>
		<br>
		<button name="save", value="save", type="submit", class="btn btn-success">Save Question</button>
	</form>
{% endblock %}

polls/templates/polls/results.html

{% extends "main/base.html" %}

{% block title %}
Result page
{% endblock %}

{% load static %}

<h1>{{ question.question_text }}</h1>

{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<style>
    * {
      box-sizing: border-box;
    }
    
    /* Create two equal columns that floats next to each other */
    .column {
      float: left;
      width: 25%;
      padding: 10px;
      height: 100px; /* Should be removed. Only for demonstration */
    }
    .left {
        width : 80%
    }
    
    .right {
        width : 20%
    }
    /* Clear floats after the columns */
    .row:after {
      content: "";
      display: table;
      clear: both;
    }
</style>
<ul>
{% for choice in question.choice_set.all %}
<div class="row">
    <div class="column left" style="background-color:#aaa;">{{ choice.choice_text }}</div>
    <div class="column right" style="background-color:#bbb;">{{ choice.votes }}</div>
</div>
{% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Vote another question?</a>
{% endblock %}